
module.exports = [
    {
        name: "Danish Waseem",
        role: "Convener",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996129/Roto/1_alcigs.png",
        gmail: "danish.waseem@outlook.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "Liz George",
        role: "President",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996124/Roto/2_vharza.png",
        gmail: "lizgeorge00@hotmail.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "Akshat Nambiar",
        role: "Secretary",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641995993/Roto/3_q9vxll.png",
        gmail: "akshat1804@gmail.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "Sanjo Sabu",
        role: "Joint Convenor",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996034/Roto/4_hunpqj.png",
        gmail: "sanjosabu00@gmail.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "Amaan Siyad",
        role: "Vice President",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641995985/Roto/5_fi72ey.png",
        gmail: "amaansiyad24@gmail.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "Suraj Shenoy",
        role: "Joint Secretary",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641995970/Roto/6_inttf0.png",
        gmail: "suraj2shenoy@gmail.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "Vaishanav Ajay",
        role: "Sergeant at Arms",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641995990/Roto/7_xtw6v5.png",
        gmail: "vaishnavajai@gmail.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "Gaurav Hore",
        role: "Director Vocational Services",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641995999/Roto/8_quknht.png",
        gmail: "gauravhore@gmail.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "Sarath Edaparambil",
        role: "Director Community Services",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641995999/Roto/9_fhkhtt.png",
        gmail: "sarath27e@gmail.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "Abhishek Kolari",
        role: "Chairman Public Relations",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996000/Roto/10_p3gflm.png",
        gmail: "abhishek.kolari@gmail.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "Siddharth Soy",
        role: "Director of Youth Services",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996000/Roto/11_zii1o1.png",
        gmail: "siddharthsoy@gmail.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "Mohit Khandate",
        role: "Chairman Technical",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996019/Roto/12_yzy4wu.png",
        gmail: "mohit.mkhandate.946@gmail.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "Olan pinto",
        role: "Director International Affairs",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996145/Roto/13_jr5qz3.png",
        gmail: "olanpinto@gmail.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "Girish Jeswani",
        role: "Web Coordinator",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996011/Roto/14_fw9j3y.png",
        gmail: "girish_jeswani@live.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "L Nayanish",
        role: "Editor",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996005/Roto/15_gpyc21.png",
        gmail: "nayanishal@protonmail.com",
        insta: "",
        linkedIn: "",
    },
    {
        name: "Devina Kant",
        role: "Treasurer",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996011/Roto/16_wjxkgp.png",
        gmail: "devinakant@gmail.com",
        insta: "",
        linkedIn: "",
    },
];