
module.exports = [
    {
        name: "Danish Waseem",
        role: "Convener",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996129/Roto/1_alcigs.png",
        gmail: "danish.waseem@outlook.com",
        insta: "https://www.instagram.com/hashtag_danish/",
        linkedIn: "https://www.linkedin.com/in/danish-waseem-43b895192/",
    },
    {
        name: "Liz George",
        role: "President",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996124/Roto/2_vharza.png",
        gmail: "lizgeorge00@hotmail.com",
        insta: "https://www.instagram.com/lizgeorge00/",
        linkedIn: "https://www.linkedin.com/in/liz-george-663a1719b/",
    },
    {
        name: "Akshat Nambiar",
        role: "Secretary",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641995993/Roto/3_q9vxll.png",
        gmail: "akshat1804@gmail.com",
        insta: "https://www.instagram.com/aks1804/",
        linkedIn: "https://www.linkedin.com/in/akshat-nambiar-353102166/",
    },
    {
        name: "Sanjo Sabu",
        role: "Joint Convenor",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996034/Roto/4_hunpqj.png",
        gmail: "sanjosabu00@gmail.com",
        insta: "https://www.instagram.com/sanjo_bas/",
        linkedIn: "https://www.linkedin.com/in/sanjo-sabu-555370184",
    },
    {
        name: "Amaan Siyad",
        role: "Vice President",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641995985/Roto/5_fi72ey.png",
        gmail: "amaansiyad24@gmail.com",
        insta: "",
        linkedIn: "https://www.linkedin.com/in/amaan-siyad-a695041b9/",
    },
    {
        name: "Suraj Shenoy",
        role: "Joint Secretary",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641995970/Roto/6_inttf0.png",
        gmail: "suraj2shenoy@gmail.com",
        insta: "",
        linkedIn: "https://www.linkedin.com/in/suraj-shenoy-169785201/",
    },
    {
        name: "Vaishanav Ajay",
        role: "Sergeant at Arms",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641995990/Roto/7_xtw6v5.png",
        gmail: "vaishnavajai@gmail.com",
        insta: "https://www.instagram.com/vaishnav.16/",
        linkedIn: "https://www.linkedin.com/in/vaishnavajai",
    },
    {
        name: "Gaurav Hore",
        role: "Director Vocational Services",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641995999/Roto/8_quknht.png",
        gmail: "gauravhore@gmail.com",
        insta: "",
        linkedIn: "https://www.linkedin.com/in/gaurav-hore-2608271b9",
    },
    {
        name: "Sarath Edaparambil",
        role: "Director Community Services",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641995999/Roto/9_fhkhtt.png",
        gmail: "sarath27e@gmail.com",
        insta: "",
        linkedIn: "https://www.linkedin.com/in/sarath-edaparambil-3a61521b9/",
    },
    {
        name: "Abhishek Kolari",
        role: "Chairman Public Relations",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996000/Roto/10_p3gflm.png",
        gmail: "abhishek.kolari@gmail.com",
        insta: "https://www.instagram.com/abhishek_kolari/",
        linkedIn: "https://girish-j04.github.io/rotonitk/",
    },
    {
        name: "Siddharth Soy",
        role: "Director of Youth Services",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996000/Roto/11_zii1o1.png",
        gmail: "siddharthsoy@gmail.com",
        insta: "",
        linkedIn: "https://www.linkedin.com/in/siddharth-soy-a45361194/",
    },
    {
        name: "Mohit Khandate",
        role: "Chairman Technical",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996019/Roto/12_yzy4wu.png",
        gmail: "mohit.mkhandate.946@gmail.com",
        insta: "https://www.instagram.com/mohitmk7/",
        linkedIn: "https://www.linkedin.com/in/mohit-khandate/",
    },
    {
        name: "Olan pinto",
        role: "Director International Affairs",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996145/Roto/13_jr5qz3.png",
        gmail: "olanpinto@gmail.com",
        insta: "",
        linkedIn: "https://www.linkedin.com/in/olan-pinto-442a5b192",
    },
    {
        name: "Girish Jeswani",
        role: "Web Coordinator",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996011/Roto/14_fw9j3y.png",
        gmail: "girish_jeswani@live.com",
        insta: "https://www.instagram.com/girish._.j/",
        linkedIn: "https://girish-j04.github.io/rotonitk/",
    },
    {
        name: "L Nayanish",
        role: "Editor",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996005/Roto/15_gpyc21.png",
        gmail: "nayanishal@protonmail.com",
        insta: "",
        linkedIn: "https://girish-j04.github.io/rotonitk/",
    },
    {
        name: "Devina Kant",
        role: "Treasurer",
        imageURL: "https://res.cloudinary.com/noo-company/image/upload/v1641996011/Roto/16_wjxkgp.png",
        gmail: "devinakant@gmail.com",
        insta: "https://www.instagram.com/devina_kant/",
        linkedIn: "http://www.linkedin.com/in/devina-kant-4919a81a2",
    },
];